# Deploy using JamesIves/github-pages-deploy-action
name: Deploy with JamesIves Action

on:
  push:
    branches:
      - dev
  workflow_dispatch:

env:
  NODE_VERSION: '22'

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node 🔧
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install and Build 🔨
        run: |
          npm install
          npx astro build
          echo "dev.geoffmiller.cloud" > dist/CNAME
          touch dist/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: master # The branch the action should deploy to
          folder: dist # The folder the action should deploy
          clean: true # Automatically remove deleted files from the deploy branch
          force: true # Force push
          single-commit: true # Use orphan commit